%MATLAB Code from Radar Waveform Analyzer App

%Generated by MATLAB 8.1 and Phased Array System Toolbox 2.0

%Generated on 06-Mar-2013 09:51:34

% Create a system object

h = phased.LinearFMWaveform;
% Set the values of the properties
h.SampleRate =  6000000;
h.PulseWidth = 6.67e-06;
h.PRF = 15000;
h.SweepBandwidth = 3000000;
h.SweepDirection = 'Up';
h.SweepInterval = 'Positive';
h.Envelope = 'Rectangular';
h.NumPulses = 1;
% Generate the plot
Fs = h.SampleRate;
x = step(h);
l = (0:length(x)-1)/Fs;
subplot(2,1,1);
plot(l,real(x));
xlabel('Time (s)');
ylabel('Amplitude (v)');
title('Waveform: Real Part');
grid on;
subplot(2,1,2);
plot(l,imag(x));
xlabel('Time (s)');
ylabel('Amplitude (v)');
title('Waveform: Imaginary Part');
grid on;


