function x = waveform_rect()

persistent hwav

if isempty(hwav)
    hwav = phased.RectangularWaveform(...
    'PulseWidth',1/3e6,...
    'PRF',3e4,...
    'SampleRate',6e6,...
    'OutputFormat','Samples',...
    'NumSamples',1);
end

x = step(hwav);