function x = waveform_lfm()

persistent hwav

if isempty(hwav)
    hwav = phased.LinearFMWaveform(...
    'SweepBandwidth',3e6,...
    'PulseWidth',20/3e6,...
    'PRF',3e4,...
    'SampleRate',6e6,...
    'OutputFormat','Samples',...
    'NumSamples',1);
end

x = step(hwav);