clear;
close;
load('DataCube.mat');
DataCube = xrv;
nfft_r = 2^nextpow2(size(xrv,1));
nfft_d = 2^nextpow2(size(xrv,3));

Data_Cube_Imaging(DataCube,...
                  nfft_r,...
                  nfft_d,...
                  fc,...
                  fs,...
                  SweepTime,...
                  SweepBandwidth,...
                  Nt,...
                  Nr,...
                  RD_Th);